server:
  port: 8082

spring:
  application:
    name: reservation-api
  docker:
    compose:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/closed_sarc_db
    username: closed_sarc
    password: closed_sarc
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  prometheus:
    metrics:
      export:
        enabled: true
