server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/closed_sarc_db
    username: closed_sarc
    password: closed_sarc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

# Configurações para comunicação com reservation-api
reservation-api:
  base-url: http://reservation-api:8082
  username: master@reservation.com
  password: master123
